### ISSUE TITLE
http://mirsv.com:5000/monthall 이슈, 요청

### ISSUE THREAD

**Issue by kohbwoo** [Air-Alarm/Air-Alarm-newServer#5]
이슈 
9월 9일 이전 값이 없음,
9월 9일, 9월 14일 내용이 다수 중복되는 이슈

요청
월간 그래프 구현을 위한 요청
월간 그래프 작성 테스트를 위해 9월 1일 ~ 9월 14일 까지 데이터를 임의로 생성해 json 출력 가능하도록 만들어주세요.
실질적인 사용을 기반으로 그래프 테스트와 시연영상 촬영을 위해 가능한 범위의 값을 넣어주세요.

2021년 9월 실내 측정값 일간 평균 이상(ideal) 범위
온도 20~25
습도 20~80
미세먼지 5 ~ 50
이산화탄소 350~600

창작의 고통이 있다면 아래 정보를 참고하여 작성하세요
지난 기온 정보는 아래 링크에서 볼 수 있습니다.
https://www.weather.go.kr/w/obs-climate/land/past-obs/obs-by-day.do?stn=108&yy=2021&mm=9&obs=1
습도는 강수량을 고려해 작성 가능
미세먼지와 이산화탄소 수치는 는 창작하십시오.

**Comment by SonChangHa** [comment]
완료 및 dayall로 이름 바뀜
